export default {
  GET_USER: "GET_USER",
  GET_AUTHORIZATION: "GET_AUTHORIZATION",
  ADD_AUTHORIZATION: "ADD_AUTHORIZATION",
  ADD_MEMBERSHIPS: "ADD_MEMBERSHIPS",
  ADD_BUNGIENETUSER: "ADD_BUNGIENETUSER",
  LOGOUT: "LOGOUT"
};