export default {
  GET_USER: "GET_USER",
  GET_AUTHORIZATION: "GET_AUTHORIZATION",
  ADD_AUTHORIZATION: "ADD_AUTHORIZATION",
  ADD_MEMBERSHIPS: "ADD_MEMBERSHIPS",
  ADD_BUNGIENETUSER: "ADD_BUNGIENETUSER",
  ADD_CHARACTERS: "ADD_CHARACTERS",
  ADD_CHARACTERS_SELECTED: "ADD_CHARACTERS_SELECTED",
  ADD_EQUIPMENT: "ADD_EQUIPMENT",
  DATA_ACCOUNT: "DATA_ACCOUNT",
  LOGOUT: "LOGOUT"
};